name: "PROD DEPLOY"

on:
  push:
    branches: 
        - main

permissions:
  id-token: write
  contents: read

jobs:
    terraform:
        uses: ./.github/workflows/terraform.yml
        with:
            environment: prod
            aws-assume-role-arn: "arn:aws:iam::966289686473:role/github-actions-wesllanSilva-pipeline"
            aws-region: "sa-east-1"
            aws-statefile-S3-bucket: "wesllansilva-sa-east-1-terraform-statefile"
            aws-lock-dynamodb-table: "wesllansilva-sa-east-1-terraform-lock"

