name: "Terraform Workflow"

on:
  workflow_call:
    inputs:
      environment:
        description: "Ambiente para deployment (ex: dev, staging, prod)"
        required: true
        type: string
      aws-assume-role-arn:
        description: "ARN da role do AWS para assumir"
        required: true
        type: string
      aws-region:
        description: "Região AWS para deployment"
        required: true
        type: string
      aws-statefile-S3-bucket:
        description: "Nome do bucket S3 para armazenar o state file do Terraform"
        required: true
        type: string
      aws-lock-dynamodb-table:
        description: "Nome da tabela DynamoDB para lock do Terraform"
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3


      - name: "Configurar AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-assume-role-arn }}
          role-session-name: "GitHub_to_AWS_via_FederatedOIDC"
          aws-region: ${{ inputs.aws-region }}

          
      - name: "Read destroy configuration"
        id: read-destroy-config
        run: |
          DESTROY_CONFIG="$(jq -r '.${{ inputs.environment }}' ./infra/destroy_config.json)"
            echo "DESTROY_CONFIG=$(DESTROY_CONFIG)" >> $GITHUB_OUTPUT

      
      - name: "Terraform Init"
        run: |
          cd infra && terraform init \
            -backend-config="bucket=${{ inputs.aws-statefile-S3-bucket }}" \
            -backend-config="key=${{ github.event.repository.name }}"\
            -backend-config="region=${{ inputs.aws-region }}" \
            -backend-config="dynamodb_table=${{ inputs.aws-lock-dynamodb-table }}"

      - name: "Terraform Validate"
        run: |
          terraform validate

      - name: "Terraform Destroy"
        if: steps.read-destroy-config.outputs.DESTROY_CONFIG == 'true'
        run: cd infra &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform destroy -var-file="./envs/${{ inputs.environment }}/terraform.tfvars" -auto-approve

      - name: "Terraform Plan"
        if: steps.read-destroy-config.outputs.DESTROY_CONFIG != 'true'
        id: terraform-plan
        run: cd infra &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform plan -var-file="./envs/${{ inputs.environment }}/terraform.tfvars" -out=${{ inputs.environment }}.plan

      - name: "Terraform Apply"
        if: steps.read-destroy-config.outputs.DESTROY_CONFIG != 'true'
        id: terraform-apply
        run: cd infra &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform apply "${{ inputs.environment }}.plan"